build: off
configuration: Release
environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"
platform:
  - x86
  - x64
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
