name: CI

on:
  - push
  - pull_request

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
          - x86
        node:
          - 14
          - 16
          - 18
          - 19
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - arch: x86
            os: macos-latest
          - arch: x86
            os: ubuntu-latest
          - arch: x86
            node: 18
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
  build:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
          - x86
        os:
          - macos-latest
          - ubuntu-18.04
          - windows-latest
        exclude:
          - arch: x86
            os: macos-latest
          - arch: x86
            os: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm run prebuild-darwin-x64+arm64
        if: matrix.os == 'macos-latest'
      - run: |
          npm run prebuild
          npm run prebuild-linux-musl-x64
        if: matrix.os == 'ubuntu-18.04'
      - run: npm run prebuild
        if: matrix.os == 'windows-latest'
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: prebuilds
          retention-days: 1
  release:
    needs: build
    permissions:
      contents: write # Needed for softprops/action-gh-release.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: prebuilds
      - run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: get_version
      - run:
          tar -cvf "${{ steps.get_version.outputs.version
          }}-darwin-x64+arm64.tar" -C "prebuilds/macos-latest" .
      - run:
          tar -cvf "${{ steps.get_version.outputs.version }}-linux-x64.tar" -C
          "prebuilds/ubuntu-18.04" linux-x64
      - run:
          tar -cvf "${{ steps.get_version.outputs.version }}-win32-ia32.tar" -C
          "prebuilds/windows-latest" win32-ia32
      - run:
          tar -cvf "${{ steps.get_version.outputs.version }}-win32-x64.tar" -C
          "prebuilds/windows-latest" win32-x64
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get_version.outputs.version }}-*.tar
          token: ${{ secrets.GITHUB_TOKEN }}
